# Generated by Django 3.2.15 on 2022-10-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-created_at']},
        ),
    ]
