# Generated by Django 3.2.15 on 2022-09-15 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_post_bxv0mn.jpg', upload_to='images/')),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HGH', 'High'), ('CRT', 'Critical')], default='LOW', max_length=3)),
                ('category', models.CharField(choices=[('BUG', 'Bug'), ('NAB', 'Not a Bug'), ('DUP', 'Duplicate'), ('WFX', "Won't Fix")], default='BUG', max_length=3)),
                ('state', models.CharField(choices=[('OPN', 'Open'), ('ASN', 'Assigned'), ('CLS', 'Closed')], default='OPN', max_length=3)),
                ('overdue', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='issue_assigned', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
