# Generated by Django 3.2.15 on 2022-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
