# Generated by Django 3.2.15 on 2022-10-13 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_due_date'),
        ('followers', '0004_auto_20220923_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='issue_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_following', to='issues.issue'),
        ),
    ]
