# Generated by Django 3.2.15 on 2022-10-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0005_alter_follower_issue_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
    ]
